name: Build and Push Docker Image on Tag

on:
  push:
    tags:
      - '*'  # Triggers on all tags

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t letwebsoftware/auth-service:${{ github.ref_name }} .

      - name: Push Docker image
        run: |
          docker push letwebsoftware/auth-service:${{ github.ref_name }}