name: Node.js CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          # The MySQL docker container requires these environment variables to be set
          # so we can create and migrate the test database.
          # See: https://hub.docker.com/_/mysql
          MYSQL_DATABASE: test_db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          # The root password is required for the MySQL client to connect
          # to the MySQL server.
          # See: https://hub.docker.com/_/mysql
          MYSQL_ROOT_PASSWORD: testrootpass
        ports:
          # Opens port 3306 on service container and host
          # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
          - 3306:3306
          # Before continuing, verify the mysql container is reachable from the ubuntu host
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run tests
        env:
          NODE_ENV: test
          MYSQL_TEST_CONNECTION_STRING: mysql://testuser:testpass@localhost:3306/test_db
          JWT_SECRET: testsecret
          PASSWORD_SALT: testSalt
          PASSWORD_HASH_ALGORITHM: sha256
        run: npm test
  build-docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t letwebsoftware/auth-service:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push letwebsoftware/auth-service:${{ github.sha }}